### PR TITLE
Make it easier for you/issue creators to make easily readable issues.

### PR DESCRIPTION
**Pull request by pahakalle**
Ask if you need anything changed or if you don't need this just close it 😛 

[How this file works](https://github.com/blog/2111-issue-and-pull-request-templates)

### CODE REVIEW

**Comment by pahakalle** [comment]
These are just meant to be suggestions to ease out the understanding of issues.

**Comment by pahakalle** [comment]
ping @Darkosto

**Comment by PrinceOfAmber** [comment]
I am a big fan off issue templates in general.

I would add a section on top to put in the version number it was reported as (yeah i know the version will be in the log, but for smaller issues and suggestions there will be no log).

**Comment by pahakalle** [comment]
@PrinceOfAmber Now that it got merged you can add it 👍 (i can't seem to find a good way to add it to it 😛 )

**Pull request merged**
